# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  jsoncpp_config = debug
  zlib_config = debug
  libzip_config = debug
  libzippp_config = debug
  Curlse_config = debug

else ifeq ($(config),release)
  jsoncpp_config = release
  zlib_config = release
  libzip_config = release
  libzippp_config = release
  Curlse_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := jsoncpp zlib libzip libzippp Curlse

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

jsoncpp:
ifneq (,$(jsoncpp_config))
	@echo "==== Building jsoncpp ($(jsoncpp_config)) ===="
	@${MAKE} --no-print-directory -C build/jsoncpp -f Makefile config=$(jsoncpp_config)
endif

zlib:
ifneq (,$(zlib_config))
	@echo "==== Building zlib ($(zlib_config)) ===="
	@${MAKE} --no-print-directory -C zlib -f Makefile config=$(zlib_config)
endif

libzip:
ifneq (,$(libzip_config))
	@echo "==== Building libzip ($(libzip_config)) ===="
	@${MAKE} --no-print-directory -C build/libzip -f Makefile config=$(libzip_config)
endif

libzippp:
ifneq (,$(libzippp_config))
	@echo "==== Building libzippp ($(libzippp_config)) ===="
	@${MAKE} --no-print-directory -C build/libzippp -f Makefile config=$(libzippp_config)
endif

Curlse:
ifneq (,$(Curlse_config))
	@echo "==== Building Curlse ($(Curlse_config)) ===="
	@${MAKE} --no-print-directory -C . -f Curlse.make config=$(Curlse_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/jsoncpp -f Makefile clean
	@${MAKE} --no-print-directory -C zlib -f Makefile clean
	@${MAKE} --no-print-directory -C build/libzip -f Makefile clean
	@${MAKE} --no-print-directory -C build/libzippp -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Curlse.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   jsoncpp"
	@echo "   zlib"
	@echo "   libzip"
	@echo "   libzippp"
	@echo "   Curlse"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"